//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 标准构件信息表
    /// </summary>
    [Table("TbBzhGjInfo")]
    [Serializable]
    public partial class TbBzhGjInfo : Entity
    {
        #region Model
		private int _ID;
		private string _ProCode;
		private string _ComponentCode;
		private string _ComponentName;
		private string _ComponentType;
		private string _MeteringUnit;
		private string _Remark;
		private string _InsertUserCode;
		private DateTime? _InsertTime;
		private string _SpecificationModel;
		private string _DataSources;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 项目编号
		/// </summary>
		[Field("ProCode")]
		public string ProCode
		{
			get{ return _ProCode; }
			set
			{
				this.OnPropertyValueChange("ProCode");
				this._ProCode = value;
			}
		}
		/// <summary>
		/// 构件编号
		/// </summary>
		[Field("ComponentCode")]
		public string ComponentCode
		{
			get{ return _ComponentCode; }
			set
			{
				this.OnPropertyValueChange("ComponentCode");
				this._ComponentCode = value;
			}
		}
		/// <summary>
		/// 构件名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 构件类型
		/// </summary>
		[Field("ComponentType")]
		public string ComponentType
		{
			get{ return _ComponentType; }
			set
			{
				this.OnPropertyValueChange("ComponentType");
				this._ComponentType = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeteringUnit")]
		public string MeteringUnit
		{
			get{ return _MeteringUnit; }
			set
			{
				this.OnPropertyValueChange("MeteringUnit");
				this._MeteringUnit = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 录入人编号
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime? InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 规格型号
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 数据来源
		/// </summary>
		[Field("DataSources")]
		public string DataSources
		{
			get{ return _DataSources; }
			set
			{
				this.OnPropertyValueChange("DataSources");
				this._DataSources = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProCode,
				_.ComponentCode,
				_.ComponentName,
				_.ComponentType,
				_.MeteringUnit,
				_.Remark,
				_.InsertUserCode,
				_.InsertTime,
				_.SpecificationModel,
				_.DataSources,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProCode,
				this._ComponentCode,
				this._ComponentName,
				this._ComponentType,
				this._MeteringUnit,
				this._Remark,
				this._InsertUserCode,
				this._InsertTime,
				this._SpecificationModel,
				this._DataSources,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbBzhGjInfo");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbBzhGjInfo", "ID");
            /// <summary>
			/// 项目编号
			/// </summary>
			public readonly static Field ProCode = new Field("ProCode", "TbBzhGjInfo", "项目编号");
            /// <summary>
			/// 构件编号
			/// </summary>
			public readonly static Field ComponentCode = new Field("ComponentCode", "TbBzhGjInfo", "构件编号");
            /// <summary>
			/// 构件名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbBzhGjInfo", "构件名称");
            /// <summary>
			/// 构件类型
			/// </summary>
			public readonly static Field ComponentType = new Field("ComponentType", "TbBzhGjInfo", "构件类型");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeteringUnit = new Field("MeteringUnit", "TbBzhGjInfo", "计量单位");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbBzhGjInfo", "备注");
            /// <summary>
			/// 录入人编号
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbBzhGjInfo", "录入人编号");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbBzhGjInfo", "录入时间");
            /// <summary>
			/// 规格型号
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbBzhGjInfo", "规格型号");
            /// <summary>
			/// 数据来源
			/// </summary>
			public readonly static Field DataSources = new Field("DataSources", "TbBzhGjInfo", "数据来源");
        }
        #endregion
	}
}