//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 标准化管理库
    /// </summary>
    [Table("TbBzhGlKu")]
    [Serializable]
    public partial class TbBzhGlKu : Entity
    {
        #region Model
		private int _ID;
		private string _ProCode;
		private string _ProName;
		private string _ParentProCode;
		private string _Remark;
		private string _InsertUserCode;
		private DateTime? _InsertTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 项目编号
		/// </summary>
		[Field("ProCode")]
		public string ProCode
		{
			get{ return _ProCode; }
			set
			{
				this.OnPropertyValueChange("ProCode");
				this._ProCode = value;
			}
		}
		/// <summary>
		/// 项目名称
		/// </summary>
		[Field("ProName")]
		public string ProName
		{
			get{ return _ProName; }
			set
			{
				this.OnPropertyValueChange("ProName");
				this._ProName = value;
			}
		}
		/// <summary>
		/// 上级项目编号
		/// </summary>
		[Field("ParentProCode")]
		public string ParentProCode
		{
			get{ return _ParentProCode; }
			set
			{
				this.OnPropertyValueChange("ParentProCode");
				this._ParentProCode = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 录入人编号
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime? InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProCode,
				_.ProName,
				_.ParentProCode,
				_.Remark,
				_.InsertUserCode,
				_.InsertTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProCode,
				this._ProName,
				this._ParentProCode,
				this._Remark,
				this._InsertUserCode,
				this._InsertTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbBzhGlKu");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbBzhGlKu", "ID");
            /// <summary>
			/// 项目编号
			/// </summary>
			public readonly static Field ProCode = new Field("ProCode", "TbBzhGlKu", "项目编号");
            /// <summary>
			/// 项目名称
			/// </summary>
			public readonly static Field ProName = new Field("ProName", "TbBzhGlKu", "项目名称");
            /// <summary>
			/// 上级项目编号
			/// </summary>
			public readonly static Field ParentProCode = new Field("ParentProCode", "TbBzhGlKu", "上级项目编号");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbBzhGlKu", "备注");
            /// <summary>
			/// 录入人编号
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbBzhGlKu", "录入人编号");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbBzhGlKu", "录入时间");
        }
        #endregion
	}
}