//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbRawMaterialType。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbRawMaterialType")]
    [Serializable]
    public partial class TbRawMaterialType : Entity
    {
        #region Model
		private int _ID;
		private string _TypeCode;
		private string _TypeName;
		private int? _Sort;
		private string _Remarks;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TypeCode")]
		public string TypeCode
		{
			get{ return _TypeCode; }
			set
			{
				this.OnPropertyValueChange("TypeCode");
				this._TypeCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TypeName")]
		public string TypeName
		{
			get{ return _TypeName; }
			set
			{
				this.OnPropertyValueChange("TypeName");
				this._TypeName = value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		[Field("Sort")]
		public int? Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange("Sort");
				this._Sort = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remarks")]
		public string Remarks
		{
			get{ return _Remarks; }
			set
			{
				this.OnPropertyValueChange("Remarks");
				this._Remarks = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.TypeCode,
				_.TypeName,
				_.Sort,
				_.Remarks,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._TypeCode,
				this._TypeName,
				this._Sort,
				this._Remarks,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRawMaterialType");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRawMaterialType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeCode = new Field("TypeCode", "TbRawMaterialType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName", "TbRawMaterialType", "");
            /// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "TbRawMaterialType", "排序");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "TbRawMaterialType", "");
        }
        #endregion
	}
}