//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbRawMaterialArchives。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbRawMaterialArchives")]
    [Serializable]
    public partial class TbRawMaterialArchives : Entity
    {
        #region Model
		private int _ID;
		private string _MaterialName;
		private int? _MaterialTypeId;
		private string _Specifications;
		private decimal? _Thickness;
		private string _MaterialUnit;
		private decimal? _LossFactor;
		private decimal? _ProductQuantity;
		private string _Remarks;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialTypeId")]
		public int? MaterialTypeId
		{
			get{ return _MaterialTypeId; }
			set
			{
				this.OnPropertyValueChange("MaterialTypeId");
				this._MaterialTypeId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Specifications")]
		public string Specifications
		{
			get{ return _Specifications; }
			set
			{
				this.OnPropertyValueChange("Specifications");
				this._Specifications = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Thickness")]
		public decimal? Thickness
		{
			get{ return _Thickness; }
			set
			{
				this.OnPropertyValueChange("Thickness");
				this._Thickness = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialUnit")]
		public string MaterialUnit
		{
			get{ return _MaterialUnit; }
			set
			{
				this.OnPropertyValueChange("MaterialUnit");
				this._MaterialUnit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LossFactor")]
		public decimal? LossFactor
		{
			get{ return _LossFactor; }
			set
			{
				this.OnPropertyValueChange("LossFactor");
				this._LossFactor = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProductQuantity")]
		public decimal? ProductQuantity
		{
			get{ return _ProductQuantity; }
			set
			{
				this.OnPropertyValueChange("ProductQuantity");
				this._ProductQuantity = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remarks")]
		public string Remarks
		{
			get{ return _Remarks; }
			set
			{
				this.OnPropertyValueChange("Remarks");
				this._Remarks = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.MaterialName,
				_.MaterialTypeId,
				_.Specifications,
				_.Thickness,
				_.MaterialUnit,
				_.LossFactor,
				_.ProductQuantity,
				_.Remarks,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._MaterialName,
				this._MaterialTypeId,
				this._Specifications,
				this._Thickness,
				this._MaterialUnit,
				this._LossFactor,
				this._ProductQuantity,
				this._Remarks,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRawMaterialArchives");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialTypeId = new Field("MaterialTypeId", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Specifications = new Field("Specifications", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Thickness = new Field("Thickness", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialUnit = new Field("MaterialUnit", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LossFactor = new Field("LossFactor", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductQuantity = new Field("ProductQuantity", "TbRawMaterialArchives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "TbRawMaterialArchives", "");
        }
        #endregion
	}
}