//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 模型上传信息
    /// </summary>
    [Table("TbModelOrg")]
    [Serializable]
    public partial class TbModelOrg : Entity
    {
        #region Model
		private int _ID;
		private string _SiteCode;
		private string _Path;
		private int _Type;
		private string _ProjectId;
		private string _Remark;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 文件路径
		/// </summary>
		[Field("Path")]
		public string Path
		{
			get{ return _Path; }
			set
			{
				this.OnPropertyValueChange("Path");
				this._Path = value;
			}
		}
		/// <summary>
		/// _1模型文件 2数据文件
		/// </summary>
		[Field("Type")]
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 项目Id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.SiteCode,
				_.Path,
				_.Type,
				_.ProjectId,
				_.Remark,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._SiteCode,
				this._Path,
				this._Type,
				this._ProjectId,
				this._Remark,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbModelOrg");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbModelOrg", "");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbModelOrg", "站点编号");
            /// <summary>
			/// 文件路径
			/// </summary>
			public readonly static Field Path = new Field("Path", "TbModelOrg", "文件路径");
            /// <summary>
			/// _1模型文件 2数据文件
			/// </summary>
			public readonly static Field Type = new Field("Type", "TbModelOrg", "_1模型文件 2数据文件");
            /// <summary>
			/// 项目Id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbModelOrg", "项目Id");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbModelOrg", "");
        }
        #endregion

        #region 扩展字段
        public string SiteName { get; set; }
		public string WorkArea { get; set; }
		public string Branch { get; set; }
		#endregion
	}
}