//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    ///  模型构件附加信息
    /// </summary>
    [Table("TbModelOtherInfo")]
    [Serializable]
    public partial class TbModelOtherInfo : Entity
    {
        #region Model
		private int _ID;
		private string _ComponentCode;
		private DateTime _PlanTime;
		private DateTime? _ActualTime;
		private string _Remark;
		private int _Type;
		private string _SiteCode;
		private string _ProjectId;
		private bool _IsOver;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 构建编码
		/// </summary>
		[Field("ComponentCode")]
		public string ComponentCode
		{
			get{ return _ComponentCode; }
			set
			{
				this.OnPropertyValueChange("ComponentCode");
				this._ComponentCode = value;
			}
		}
		/// <summary>
		/// 计划完成时间
		/// </summary>
		[Field("PlanTime")]
		public DateTime PlanTime
		{
			get{ return _PlanTime; }
			set
			{
				this.OnPropertyValueChange("PlanTime");
				this._PlanTime = value;
			}
		}
		/// <summary>
		/// 实际完成时间
		/// </summary>
		[Field("ActualTime")]
		public DateTime? ActualTime
		{
			get{ return _ActualTime; }
			set
			{
				this.OnPropertyValueChange("ActualTime");
				this._ActualTime = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// _1:分类 2:明细
		/// </summary>
		[Field("Type")]
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 项目Id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsOver")]
		public bool IsOver
		{
			get{ return _IsOver; }
			set
			{
				this.OnPropertyValueChange("IsOver");
				this._IsOver = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ComponentCode,
				_.PlanTime,
				_.ActualTime,
				_.Remark,
				_.Type,
				_.SiteCode,
				_.ProjectId,
				_.IsOver,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ComponentCode,
				this._PlanTime,
				this._ActualTime,
				this._Remark,
				this._Type,
				this._SiteCode,
				this._ProjectId,
				this._IsOver,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbModelOtherInfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbModelOtherInfo", "");
            /// <summary>
			/// 构建编码
			/// </summary>
			public readonly static Field ComponentCode = new Field("ComponentCode", "TbModelOtherInfo", "构建编码");
            /// <summary>
			/// 计划完成时间
			/// </summary>
			public readonly static Field PlanTime = new Field("PlanTime", "TbModelOtherInfo", "计划完成时间");
            /// <summary>
			/// 实际完成时间
			/// </summary>
			public readonly static Field ActualTime = new Field("ActualTime", "TbModelOtherInfo", "实际完成时间");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbModelOtherInfo", "备注");
            /// <summary>
			/// _1:分类 2:明细
			/// </summary>
			public readonly static Field Type = new Field("Type", "TbModelOtherInfo", "_1:分类 2:明细");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbModelOtherInfo", "站点编号");
            /// <summary>
			/// 项目Id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbModelOtherInfo", "项目Id");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsOver = new Field("IsOver", "TbModelOtherInfo", "");
        }
        #endregion

        #region 扩展字段

		/// <summary>
		/// 差额
		/// </summary>
        public int Difference { get; set; }
        public bool AllWrite { get; set; }
        public string ComponentCodeShow { get; set; }
		public string Size { get; set; }
        public int TotalCount { get; set; }
        #endregion
    }
}