//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 模型基础信息表
    /// </summary>
    [Table("TbModel_Property")]
    [Serializable]
    public partial class TbModel_Property : Entity
    {
        #region Model
		private string _ID;
		private string _SiteCode;
		private string _ProjectId;
		private string _Major;
		private string _System;
		private string _Subsystem;
		private string _MaterialType;
		private string _Material;
		private string _ComponentCode;
		private string _ComponentName;
		private string _Size;
		private string _Area;
		private string _Texture;
		private string _StationName;
		private string _Length;
		private string _FGLength;
		private string _SystemType;
		private string _Position;
		private string _DrawingNo;
		private bool _IsOrder;
		private string _FileName;
		private string _Other1;
		private string _Other2;
		private string _Other3;
		private string _Other4;
		private string _Other5;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 专业
		/// </summary>
		[Field("Major")]
		public string Major
		{
			get{ return _Major; }
			set
			{
				this.OnPropertyValueChange("Major");
				this._Major = value;
			}
		}
		/// <summary>
		/// 大系统
		/// </summary>
		[Field("System")]
		public string System
		{
			get{ return _System; }
			set
			{
				this.OnPropertyValueChange("System");
				this._System = value;
			}
		}
		/// <summary>
		/// 小系统
		/// </summary>
		[Field("Subsystem")]
		public string Subsystem
		{
			get{ return _Subsystem; }
			set
			{
				this.OnPropertyValueChange("Subsystem");
				this._Subsystem = value;
			}
		}
		/// <summary>
		/// 材料类型
		/// </summary>
		[Field("MaterialType")]
		public string MaterialType
		{
			get{ return _MaterialType; }
			set
			{
				this.OnPropertyValueChange("MaterialType");
				this._MaterialType = value;
			}
		}
		/// <summary>
		/// 材料名称
		/// </summary>
		[Field("Material")]
		public string Material
		{
			get{ return _Material; }
			set
			{
				this.OnPropertyValueChange("Material");
				this._Material = value;
			}
		}
		/// <summary>
		/// 构件编码
		/// </summary>
		[Field("ComponentCode")]
		public string ComponentCode
		{
			get{ return _ComponentCode; }
			set
			{
				this.OnPropertyValueChange("ComponentCode");
				this._ComponentCode = value;
			}
		}
		/// <summary>
		/// 族与类型
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 尺寸
		/// </summary>
		[Field("Size")]
		public string Size
		{
			get{ return _Size; }
			set
			{
				this.OnPropertyValueChange("Size");
				this._Size = value;
			}
		}
		/// <summary>
		/// 面积
		/// </summary>
		[Field("Area")]
		public string Area
		{
			get{ return _Area; }
			set
			{
				this.OnPropertyValueChange("Area");
				this._Area = value;
			}
		}
		/// <summary>
		/// 材质
		/// </summary>
		[Field("Texture")]
		public string Texture
		{
			get{ return _Texture; }
			set
			{
				this.OnPropertyValueChange("Texture");
				this._Texture = value;
			}
		}
		/// <summary>
		/// 车站编号
		/// </summary>
		[Field("StationName")]
		public string StationName
		{
			get{ return _StationName; }
			set
			{
				this.OnPropertyValueChange("StationName");
				this._StationName = value;
			}
		}
		/// <summary>
		/// 长度
		/// </summary>
		[Field("Length")]
		public string Length
		{
			get{ return _Length; }
			set
			{
				this.OnPropertyValueChange("Length");
				this._Length = value;
			}
		}
		/// <summary>
		/// 风管长度
		/// </summary>
		[Field("FGLength")]
		public string FGLength
		{
			get{ return _FGLength; }
			set
			{
				this.OnPropertyValueChange("FGLength");
				this._FGLength = value;
			}
		}
		/// <summary>
		/// 系统类型
		/// </summary>
		[Field("SystemType")]
		public string SystemType
		{
			get{ return _SystemType; }
			set
			{
				this.OnPropertyValueChange("SystemType");
				this._SystemType = value;
			}
		}
		/// <summary>
		/// 安装位置
		/// </summary>
		[Field("Position")]
		public string Position
		{
			get{ return _Position; }
			set
			{
				this.OnPropertyValueChange("Position");
				this._Position = value;
			}
		}
		/// <summary>
		/// 图纸编号
		/// </summary>
		[Field("DrawingNo")]
		public string DrawingNo
		{
			get{ return _DrawingNo; }
			set
			{
				this.OnPropertyValueChange("DrawingNo");
				this._DrawingNo = value;
			}
		}
		/// <summary>
		/// 是否下单
		/// </summary>
		[Field("IsOrder")]
		public bool IsOrder
		{
			get{ return _IsOrder; }
			set
			{
				this.OnPropertyValueChange("IsOrder");
				this._IsOrder = value;
			}
		}
		/// <summary>
		/// 文件地址
		/// </summary>
		[Field("FileName")]
		public string FileName
		{
			get{ return _FileName; }
			set
			{
				this.OnPropertyValueChange("FileName");
				this._FileName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Other1")]
		public string Other1
		{
			get{ return _Other1; }
			set
			{
				this.OnPropertyValueChange("Other1");
				this._Other1 = value;
			}
		}
		/// <summary>
		/// Other2
		/// </summary>
		[Field("Other2")]
		public string Other2
		{
			get{ return _Other2; }
			set
			{
				this.OnPropertyValueChange("Other2");
				this._Other2 = value;
			}
		}
		/// <summary>
		/// Other3
		/// </summary>
		[Field("Other3")]
		public string Other3
		{
			get{ return _Other3; }
			set
			{
				this.OnPropertyValueChange("Other3");
				this._Other3 = value;
			}
		}
		/// <summary>
		/// Other4
		/// </summary>
		[Field("Other4")]
		public string Other4
		{
			get{ return _Other4; }
			set
			{
				this.OnPropertyValueChange("Other4");
				this._Other4 = value;
			}
		}
		/// <summary>
		/// Other5
		/// </summary>
		[Field("Other5")]
		public string Other5
		{
			get{ return _Other5; }
			set
			{
				this.OnPropertyValueChange("Other5");
				this._Other5 = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.SiteCode,
				_.ProjectId,
				_.Major,
				_.System,
				_.Subsystem,
				_.MaterialType,
				_.Material,
				_.ComponentCode,
				_.ComponentName,
				_.Size,
				_.Area,
				_.Texture,
				_.StationName,
				_.Length,
				_.FGLength,
				_.SystemType,
				_.Position,
				_.DrawingNo,
				_.IsOrder,
				_.FileName,
				_.Other1,
				_.Other2,
				_.Other3,
				_.Other4,
				_.Other5,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._SiteCode,
				this._ProjectId,
				this._Major,
				this._System,
				this._Subsystem,
				this._MaterialType,
				this._Material,
				this._ComponentCode,
				this._ComponentName,
				this._Size,
				this._Area,
				this._Texture,
				this._StationName,
				this._Length,
				this._FGLength,
				this._SystemType,
				this._Position,
				this._DrawingNo,
				this._IsOrder,
				this._FileName,
				this._Other1,
				this._Other2,
				this._Other3,
				this._Other4,
				this._Other5,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbModel_Property");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbModel_Property", "ID");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbModel_Property", "站点编号");
            /// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbModel_Property", "项目id");
            /// <summary>
			/// 专业
			/// </summary>
			public readonly static Field Major = new Field("Major", "TbModel_Property", "专业");
            /// <summary>
			/// 大系统
			/// </summary>
			public readonly static Field System = new Field("System", "TbModel_Property", "大系统");
            /// <summary>
			/// 小系统
			/// </summary>
			public readonly static Field Subsystem = new Field("Subsystem", "TbModel_Property", "小系统");
            /// <summary>
			/// 材料类型
			/// </summary>
			public readonly static Field MaterialType = new Field("MaterialType", "TbModel_Property", "材料类型");
            /// <summary>
			/// 材料名称
			/// </summary>
			public readonly static Field Material = new Field("Material", "TbModel_Property", "材料名称");
            /// <summary>
			/// 构件编码
			/// </summary>
			public readonly static Field ComponentCode = new Field("ComponentCode", "TbModel_Property", "构件编码");
            /// <summary>
			/// 族与类型
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbModel_Property", "族与类型");
            /// <summary>
			/// 尺寸
			/// </summary>
			public readonly static Field Size = new Field("Size", "TbModel_Property", "尺寸");
            /// <summary>
			/// 面积
			/// </summary>
			public readonly static Field Area = new Field("Area", "TbModel_Property", "面积");
            /// <summary>
			/// 材质
			/// </summary>
			public readonly static Field Texture = new Field("Texture", "TbModel_Property", "材质");
            /// <summary>
			/// 车站编号
			/// </summary>
			public readonly static Field StationName = new Field("StationName", "TbModel_Property", "车站编号");
            /// <summary>
			/// 长度
			/// </summary>
			public readonly static Field Length = new Field("Length", "TbModel_Property", "长度");
            /// <summary>
			/// 风管长度
			/// </summary>
			public readonly static Field FGLength = new Field("FGLength", "TbModel_Property", "风管长度");
            /// <summary>
			/// 系统类型
			/// </summary>
			public readonly static Field SystemType = new Field("SystemType", "TbModel_Property", "系统类型");
            /// <summary>
			/// 安装位置
			/// </summary>
			public readonly static Field Position = new Field("Position", "TbModel_Property", "安装位置");
            /// <summary>
			/// 图纸编号
			/// </summary>
			public readonly static Field DrawingNo = new Field("DrawingNo", "TbModel_Property", "图纸编号");
            /// <summary>
			/// 是否下单
			/// </summary>
			public readonly static Field IsOrder = new Field("IsOrder", "TbModel_Property", "是否下单");
            /// <summary>
			/// 文件地址
			/// </summary>
			public readonly static Field FileName = new Field("FileName", "TbModel_Property", "文件地址");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Other1 = new Field("Other1", "TbModel_Property", "");
            /// <summary>
			/// Other2
			/// </summary>
			public readonly static Field Other2 = new Field("Other2", "TbModel_Property", "Other2");
            /// <summary>
			/// Other3
			/// </summary>
			public readonly static Field Other3 = new Field("Other3", "TbModel_Property", "Other3");
            /// <summary>
			/// Other4
			/// </summary>
			public readonly static Field Other4 = new Field("Other4", "TbModel_Property", "Other4");
            /// <summary>
			/// Other5
			/// </summary>
			public readonly static Field Other5 = new Field("Other5", "TbModel_Property", "Other5");
        }
        #endregion
	}
}