//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbProblemOrder。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbProblemOrder")]
    [Serializable]
    public partial class TbProblemOrder : Entity
    {
        #region Model
		private int _ID;
		private string _ProblemOrderCode;
		private string _OrderCode;
		private string _Major;
		private string _SystemType;
		private string _ProcessFactoryCode;
		private string _SiteCode;
		private string _ProjectId;
		private string _OrderType;
		private string _UrgentDegree;
		private DateTime? _DistributionTime;
		private decimal? _ProblemSumNumber;
		private decimal? _SumNumber;
		private string _ChangeStatus;
		private string _ChangeType;
		private string _Remark;
		private string _Examinestatus;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime _InsertTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 问题订单编号
		/// </summary>
		[Field("ProblemOrderCode")]
		public string ProblemOrderCode
		{
			get{ return _ProblemOrderCode; }
			set
			{
				this.OnPropertyValueChange("ProblemOrderCode");
				this._ProblemOrderCode = value;
			}
		}
		/// <summary>
		/// 原订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 专业
		/// </summary>
		[Field("Major")]
		public string Major
		{
			get{ return _Major; }
			set
			{
				this.OnPropertyValueChange("Major");
				this._Major = value;
			}
		}
		/// <summary>
		/// 系统类型
		/// </summary>
		[Field("SystemType")]
		public string SystemType
		{
			get{ return _SystemType; }
			set
			{
				this.OnPropertyValueChange("SystemType");
				this._SystemType = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 订单类型
		/// </summary>
		[Field("OrderType")]
		public string OrderType
		{
			get{ return _OrderType; }
			set
			{
				this.OnPropertyValueChange("OrderType");
				this._OrderType = value;
			}
		}
		/// <summary>
		/// 紧急程度
		/// </summary>
		[Field("UrgentDegree")]
		public string UrgentDegree
		{
			get{ return _UrgentDegree; }
			set
			{
				this.OnPropertyValueChange("UrgentDegree");
				this._UrgentDegree = value;
			}
		}
		/// <summary>
		/// 要求送达时间
		/// </summary>
		[Field("DistributionTime")]
		public DateTime? DistributionTime
		{
			get{ return _DistributionTime; }
			set
			{
				this.OnPropertyValueChange("DistributionTime");
				this._DistributionTime = value;
			}
		}
		/// <summary>
		/// 问题订单件数
		/// </summary>
		[Field("ProblemSumNumber")]
		public decimal? ProblemSumNumber
		{
			get{ return _ProblemSumNumber; }
			set
			{
				this.OnPropertyValueChange("ProblemSumNumber");
				this._ProblemSumNumber = value;
			}
		}
		/// <summary>
		/// 原订单件数
		/// </summary>
		[Field("SumNumber")]
		public decimal? SumNumber
		{
			get{ return _SumNumber; }
			set
			{
				this.OnPropertyValueChange("SumNumber");
				this._SumNumber = value;
			}
		}
		/// <summary>
		/// 变更状态
		/// </summary>
		[Field("ChangeStatus")]
		public string ChangeStatus
		{
			get{ return _ChangeStatus; }
			set
			{
				this.OnPropertyValueChange("ChangeStatus");
				this._ChangeStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ChangeType")]
		public string ChangeType
		{
			get{ return _ChangeType; }
			set
			{
				this.OnPropertyValueChange("ChangeType");
				this._ChangeType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProblemOrderCode,
				_.OrderCode,
				_.Major,
				_.SystemType,
				_.ProcessFactoryCode,
				_.SiteCode,
				_.ProjectId,
				_.OrderType,
				_.UrgentDegree,
				_.DistributionTime,
				_.ProblemSumNumber,
				_.SumNumber,
				_.ChangeStatus,
				_.ChangeType,
				_.Remark,
				_.Examinestatus,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProblemOrderCode,
				this._OrderCode,
				this._Major,
				this._SystemType,
				this._ProcessFactoryCode,
				this._SiteCode,
				this._ProjectId,
				this._OrderType,
				this._UrgentDegree,
				this._DistributionTime,
				this._ProblemSumNumber,
				this._SumNumber,
				this._ChangeStatus,
				this._ChangeType,
				this._Remark,
				this._Examinestatus,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbProblemOrder");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbProblemOrder", "ID");
            /// <summary>
			/// 问题订单编号
			/// </summary>
			public readonly static Field ProblemOrderCode = new Field("ProblemOrderCode", "TbProblemOrder", "问题订单编号");
            /// <summary>
			/// 原订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbProblemOrder", "原订单编号");
            /// <summary>
			/// 专业
			/// </summary>
			public readonly static Field Major = new Field("Major", "TbProblemOrder", "专业");
            /// <summary>
			/// 系统类型
			/// </summary>
			public readonly static Field SystemType = new Field("SystemType", "TbProblemOrder", "系统类型");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbProblemOrder", "加工厂编号");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbProblemOrder", "站点编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbProblemOrder", "");
            /// <summary>
			/// 订单类型
			/// </summary>
			public readonly static Field OrderType = new Field("OrderType", "TbProblemOrder", "订单类型");
            /// <summary>
			/// 紧急程度
			/// </summary>
			public readonly static Field UrgentDegree = new Field("UrgentDegree", "TbProblemOrder", "紧急程度");
            /// <summary>
			/// 要求送达时间
			/// </summary>
			public readonly static Field DistributionTime = new Field("DistributionTime", "TbProblemOrder", "要求送达时间");
            /// <summary>
			/// 问题订单件数
			/// </summary>
			public readonly static Field ProblemSumNumber = new Field("ProblemSumNumber", "TbProblemOrder", "问题订单件数");
            /// <summary>
			/// 原订单件数
			/// </summary>
			public readonly static Field SumNumber = new Field("SumNumber", "TbProblemOrder", "原订单件数");
            /// <summary>
			/// 变更状态
			/// </summary>
			public readonly static Field ChangeStatus = new Field("ChangeStatus", "TbProblemOrder", "变更状态");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ChangeType = new Field("ChangeType", "TbProblemOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbProblemOrder", "");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbProblemOrder", "审批状态");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbProblemOrder", "附件");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbProblemOrder", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbProblemOrder", "录入时间");
        }
        #endregion
	}
}