//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbSignForDetail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbSignForDetail")]
    [Serializable]
    public partial class TbSignForDetail : Entity
    {
        #region Model
		private int _ID;
		private string _OrderCode;
		private string _PackCode;
		private string _SignFoeCode;
		private int? _OrderDetialId;
		private string _IsInstall;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 包件号
		/// </summary>
		[Field("PackCode")]
		public string PackCode
		{
			get{ return _PackCode; }
			set
			{
				this.OnPropertyValueChange("PackCode");
				this._PackCode = value;
			}
		}
		/// <summary>
		/// 签收编号
		/// </summary>
		[Field("SignFoeCode")]
		public string SignFoeCode
		{
			get{ return _SignFoeCode; }
			set
			{
				this.OnPropertyValueChange("SignFoeCode");
				this._SignFoeCode = value;
			}
		}
		/// <summary>
		/// 订单明细Id
		/// </summary>
		[Field("OrderDetialId")]
		public int? OrderDetialId
		{
			get{ return _OrderDetialId; }
			set
			{
				this.OnPropertyValueChange("OrderDetialId");
				this._OrderDetialId = value;
			}
		}
		/// <summary>
		/// 是否安装
		/// </summary>
		[Field("IsInstall")]
		public string IsInstall
		{
			get{ return _IsInstall; }
			set
			{
				this.OnPropertyValueChange("IsInstall");
				this._IsInstall = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderCode,
				_.PackCode,
				_.SignFoeCode,
				_.OrderDetialId,
				_.IsInstall,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderCode,
				this._PackCode,
				this._SignFoeCode,
				this._OrderDetialId,
				this._IsInstall,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbSignForDetail");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbSignForDetail", "ID");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbSignForDetail", "订单编号");
            /// <summary>
			/// 包件号
			/// </summary>
			public readonly static Field PackCode = new Field("PackCode", "TbSignForDetail", "包件号");
            /// <summary>
			/// 签收编号
			/// </summary>
			public readonly static Field SignFoeCode = new Field("SignFoeCode", "TbSignForDetail", "签收编号");
            /// <summary>
			/// 订单明细Id
			/// </summary>
			public readonly static Field OrderDetialId = new Field("OrderDetialId", "TbSignForDetail", "订单明细Id");
            /// <summary>
			/// 是否安装
			/// </summary>
			public readonly static Field IsInstall = new Field("IsInstall", "TbSignForDetail", "是否安装");
        }
        #endregion
	}
}