//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbWorkOrderSignFor。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbWorkOrderSignFor")]
    [Serializable]
    public partial class TbWorkOrderSignFor : Entity
    {
        #region Model
		private int _ID;
		private string _OrderCode;
		private string _PackCode;
		private string _SignForCode;
		private string _SystemType;
		private string _MaterialType;
		private string _ComponentName;
		private string _OrderDetialId;
		private int? _SignForNumber;
		private DateTime? _SignForDate;
		private string _Remark;
		private string _SignForUserCode;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 包件号
		/// </summary>
		[Field("PackCode")]
		public string PackCode
		{
			get{ return _PackCode; }
			set
			{
				this.OnPropertyValueChange("PackCode");
				this._PackCode = value;
			}
		}
		/// <summary>
		/// 签收编号
		/// </summary>
		[Field("SignForCode")]
		public string SignForCode
		{
			get{ return _SignForCode; }
			set
			{
				this.OnPropertyValueChange("SignForCode");
				this._SignForCode = value;
			}
		}
		/// <summary>
		/// 系统类型
		/// </summary>
		[Field("SystemType")]
		public string SystemType
		{
			get{ return _SystemType; }
			set
			{
				this.OnPropertyValueChange("SystemType");
				this._SystemType = value;
			}
		}
		/// <summary>
		/// 材料类型
		/// </summary>
		[Field("MaterialType")]
		public string MaterialType
		{
			get{ return _MaterialType; }
			set
			{
				this.OnPropertyValueChange("MaterialType");
				this._MaterialType = value;
			}
		}
		/// <summary>
		/// 构建名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 订单明细表id
		/// </summary>
		[Field("OrderDetialId")]
		public string OrderDetialId
		{
			get{ return _OrderDetialId; }
			set
			{
				this.OnPropertyValueChange("OrderDetialId");
				this._OrderDetialId = value;
			}
		}
		/// <summary>
		/// 签收数量
		/// </summary>
		[Field("SignForNumber")]
		public int? SignForNumber
		{
			get{ return _SignForNumber; }
			set
			{
				this.OnPropertyValueChange("SignForNumber");
				this._SignForNumber = value;
			}
		}
		/// <summary>
		/// 签收日期
		/// </summary>
		[Field("SignForDate")]
		public DateTime? SignForDate
		{
			get{ return _SignForDate; }
			set
			{
				this.OnPropertyValueChange("SignForDate");
				this._SignForDate = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 签收用户
		/// </summary>
		[Field("SignForUserCode")]
		public string SignForUserCode
		{
			get{ return _SignForUserCode; }
			set
			{
				this.OnPropertyValueChange("SignForUserCode");
				this._SignForUserCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderCode,
				_.PackCode,
				_.SignForCode,
				_.SystemType,
				_.MaterialType,
				_.ComponentName,
				_.OrderDetialId,
				_.SignForNumber,
				_.SignForDate,
				_.Remark,
				_.SignForUserCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderCode,
				this._PackCode,
				this._SignForCode,
				this._SystemType,
				this._MaterialType,
				this._ComponentName,
				this._OrderDetialId,
				this._SignForNumber,
				this._SignForDate,
				this._Remark,
				this._SignForUserCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbWorkOrderSignFor");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbWorkOrderSignFor", "ID");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbWorkOrderSignFor", "订单编号");
            /// <summary>
			/// 包件号
			/// </summary>
			public readonly static Field PackCode = new Field("PackCode", "TbWorkOrderSignFor", "包件号");
            /// <summary>
			/// 签收编号
			/// </summary>
			public readonly static Field SignForCode = new Field("SignForCode", "TbWorkOrderSignFor", "签收编号");
            /// <summary>
			/// 系统类型
			/// </summary>
			public readonly static Field SystemType = new Field("SystemType", "TbWorkOrderSignFor", "系统类型");
            /// <summary>
			/// 材料类型
			/// </summary>
			public readonly static Field MaterialType = new Field("MaterialType", "TbWorkOrderSignFor", "材料类型");
            /// <summary>
			/// 构建名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbWorkOrderSignFor", "构建名称");
            /// <summary>
			/// 订单明细表id
			/// </summary>
			public readonly static Field OrderDetialId = new Field("OrderDetialId", "TbWorkOrderSignFor", "订单明细表id");
            /// <summary>
			/// 签收数量
			/// </summary>
			public readonly static Field SignForNumber = new Field("SignForNumber", "TbWorkOrderSignFor", "签收数量");
            /// <summary>
			/// 签收日期
			/// </summary>
			public readonly static Field SignForDate = new Field("SignForDate", "TbWorkOrderSignFor", "签收日期");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbWorkOrderSignFor", "备注");
            /// <summary>
			/// 签收用户
			/// </summary>
			public readonly static Field SignForUserCode = new Field("SignForUserCode", "TbWorkOrderSignFor", "签收用户");
        }
        #endregion
	}
}