//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 加工订单
    /// </summary>
    [Table("TbWorkOrder")]
    [Serializable]
    public partial class TbWorkOrder : Entity
    {
        #region Model
		private int _ID;
		private string _OrderCode;
		private string _Major;
		private string _SystemType;
		private string _ProcessFactoryCode;
		private string _SiteCode;
		private string _OrderState;
		private string _OrderType;
		private DateTime? _DistributionTime;
		private decimal? _SumNumber;
		private string _UrgentDegree;
		private string _Remark;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime? _InsertTime;
		private string _Examinestatus;
		private string _ProjectId;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 专业
		/// </summary>
		[Field("Major")]
		public string Major
		{
			get{ return _Major; }
			set
			{
				this.OnPropertyValueChange("Major");
				this._Major = value;
			}
		}
		/// <summary>
		/// 系统类型
		/// </summary>
		[Field("SystemType")]
		public string SystemType
		{
			get{ return _SystemType; }
			set
			{
				this.OnPropertyValueChange("SystemType");
				this._SystemType = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 订单状态
		/// </summary>
		[Field("OrderState")]
		public string OrderState
		{
			get{ return _OrderState; }
			set
			{
				this.OnPropertyValueChange("OrderState");
				this._OrderState = value;
			}
		}
		/// <summary>
		/// 订单类型
		/// </summary>
		[Field("OrderType")]
		public string OrderType
		{
			get{ return _OrderType; }
			set
			{
				this.OnPropertyValueChange("OrderType");
				this._OrderType = value;
			}
		}
		/// <summary>
		/// 要求送达时间
		/// </summary>
		[Field("DistributionTime")]
		public DateTime? DistributionTime
		{
			get{ return _DistributionTime; }
			set
			{
				this.OnPropertyValueChange("DistributionTime");
				this._DistributionTime = value;
			}
		}
		/// <summary>
		/// 总件数
		/// </summary>
		[Field("SumNumber")]
		public decimal? SumNumber
		{
			get{ return _SumNumber; }
			set
			{
				this.OnPropertyValueChange("SumNumber");
				this._SumNumber = value;
			}
		}
		/// <summary>
		/// 紧急程度
		/// </summary>
		[Field("UrgentDegree")]
		public string UrgentDegree
		{
			get{ return _UrgentDegree; }
			set
			{
				this.OnPropertyValueChange("UrgentDegree");
				this._UrgentDegree = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime? InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.OrderCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderCode,
				_.Major,
				_.SystemType,
				_.ProcessFactoryCode,
				_.SiteCode,
				_.OrderState,
				_.OrderType,
				_.DistributionTime,
				_.SumNumber,
				_.UrgentDegree,
				_.Remark,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
				_.Examinestatus,
				_.ProjectId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderCode,
				this._Major,
				this._SystemType,
				this._ProcessFactoryCode,
				this._SiteCode,
				this._OrderState,
				this._OrderType,
				this._DistributionTime,
				this._SumNumber,
				this._UrgentDegree,
				this._Remark,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
				this._Examinestatus,
				this._ProjectId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbWorkOrder");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbWorkOrder", "ID");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbWorkOrder", "订单编号");
            /// <summary>
			/// 专业
			/// </summary>
			public readonly static Field Major = new Field("Major", "TbWorkOrder", "专业");
            /// <summary>
			/// 系统类型
			/// </summary>
			public readonly static Field SystemType = new Field("SystemType", "TbWorkOrder", "系统类型");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbWorkOrder", "加工厂编号");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbWorkOrder", "站点编号");
            /// <summary>
			/// 订单状态
			/// </summary>
			public readonly static Field OrderState = new Field("OrderState", "TbWorkOrder", "订单状态");
            /// <summary>
			/// 订单类型
			/// </summary>
			public readonly static Field OrderType = new Field("OrderType", "TbWorkOrder", "订单类型");
            /// <summary>
			/// 要求送达时间
			/// </summary>
			public readonly static Field DistributionTime = new Field("DistributionTime", "TbWorkOrder", "要求送达时间");
            /// <summary>
			/// 总件数
			/// </summary>
			public readonly static Field SumNumber = new Field("SumNumber", "TbWorkOrder", "总件数");
            /// <summary>
			/// 紧急程度
			/// </summary>
			public readonly static Field UrgentDegree = new Field("UrgentDegree", "TbWorkOrder", "紧急程度");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbWorkOrder", "备注");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbWorkOrder", "附件");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbWorkOrder", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbWorkOrder", "录入时间");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbWorkOrder", "审批状态");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbWorkOrder", "");
        }
        #endregion
	}
}